version: '3'

services:
  frontend:
    build: 
      context: ./frontend # Dockerfileがある場所
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on: # コンテナの依存関係を設定する(このコンテナ(frontend)より先に起動させるコンテナを設定する)
      - backend # コンテナbackendがコンテナfrontendより先に起動するように設定している

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports: 
      - "5000:5000"
    environment:
      - NODE_ENV=development

  test_db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./backend/test-db-store:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres

  # nginxはまだ自分には早かったから保留
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #     - backend